import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";
import NavBar from "../components/NavBar";
import { useEffect } from "react";
import { db } from "../firebase/clientApp";
import { doc, addDoc, collection } from "firebase/firestore";
import moment from "moment-timezone";

const generateRandomIP = () => {
  const ip =
    Math.floor(Math.random() * 255) +
    1 +
    "." +
    Math.floor(Math.random() * 255) +
    "." +
    Math.floor(Math.random() * 255) +
    "." +
    Math.floor(Math.random() * 255);

  return ip;
};

export const getServerSideProps = async ({ req }) => {
  let data = {};
  const dbRef = collection(db, "visitors");
  // get ip from headers here
  // const ip = generateRandomIP();
  const currentTime = moment().utc().format();
  const currentTimeStamp = Date.now();
  const mobile = req.headers["user-agent"].match(
    /Android|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i
  )
    ? true
    : false;

  let platform = "";
  if (req.headers["user-agent"].match(/Windows/i)) {
    platform = "Windows";
  } else if (req.headers["user-agent"].match(/Macintosh/i)) {
    platform = "Mac";
  } else if (req.headers["user-agent"].match(/Linux/i)) {
    platform = "Linux";
  }

  const country = req?.headers["x-vercel-ip-country"]
    ? req.headers["x-vercel-ip-country"]
    : "";
  const city = req?.headers["x-vercel-ip-city"]
    ? req.headers["x-vercel-ip-city"]
    : "";
  const region = req?.headers["x-vercel-ip-country-region"]
    ? req.headers["x-vercel-ip-country-region"]
    : "";
  const longitude = req?.headers["x-vercel-ip-longitude"]
    ? req.headers["x-vercel-ip-longitude"]
    : "";
  const latitude = req?.headers["x-vercel-ip-latitude"]
    ? req.headers["x-vercel-ip-latitude"]
    : "";

  let ip = req.headers["x-real-ip"];
  if (!ip) {
    const forwardedFor = req.headers["x-forwarded-for"];
    if (Array.isArray(forwardedFor)) {
      ip = forwardedFor.at(0);
    } else {
      ip = forwardedFor?.split(",").at(0) ?? "Unknown";
    }
  }

  data = {
    createdAt: currentTimeStamp,
    ip: ip,
    dateTime: currentTime,
    country: country,
    city: city,
    region: region,
    longitude: longitude,
    latitude: latitude,
    mobile: mobile,
    platform: platform,
  };

  if (req.headers["host"] != "localhost:3000") {
    const res = await addDoc(dbRef, data);
  }

  return {
    props: { data: data, headers: req.headers },
  };
};

export default function Home({ data, headers }) {
  console.log(data);
  console.log(headers);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <NavBar />
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </div>
  );
}
